### ISSUE TITLE
trainer.test() fails when using ddp

### ISSUE THREAD

**Issue by sneiman** [PyTorchLightning/pytorch-lightning#745]
Calling 'trainer.fit()' following ddp training fails giving this error:
```
  File "/home/seth/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/model_hooks.py", line 19, in is_overriden
    is_overriden = getattr(model, f_name).__code__ is not getattr(super_object, f_name).__code__
AttributeError: 'NoneType' object has no attribute 'test_step'
```
The model variable is set to None. Note that **trainer.test(model)** works fine. I had originally reported that I had some issues with this, but these turned out to be self inflicted.

Working on Ubuntu 18.04.2LTS, python 3.6.8, both pytorch 1.3, and 1.4, and both pytorch-lightning .5.3.2 and .6. 14 core, 7 gpus. No virtual environment.

Simply call trainer.test() following ddp training.

**Comment by Borda** [comment]
as mentioned in https://github.com/PyTorchLightning/pytorch-lightning/issues/746#issuecomment-578550228, I close this issue in favour to #747
