### ISSUE TITLE
backward callback does not work on pytorch-lightning version 1.0.0rc3

### ISSUE THREAD

**Issue by peymanpoozesh** [PyTorchLightning/pytorch-lightning#4069]
In pytorch-lightning version 0.10 the following code works well. However in pytorch-lightning version 1.0.0rc3, the code does not work
and gives the following error:
TypeError: backward() missing 1 required positional argument: 'optimizer_idx'

#### Code sample
```
def configure_optimizers(self):
      optimizer = optim.Adam(self.parameters(), lr=self.hparams.lr)
      return optimizer

def backward(self, trainer, loss, optimizer, optimizer_idx):
        loss.backward(retain_graph=True)

```

**Comment by awaelchli** [comment]
The new backward hook has arguments, loss, optimizer, optimizer_idx. 
You need to remove the trainer argument. 
If you need to access trainer, you can do that by self.trainer.
