### ISSUE TITLE
ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)

### ISSUE THREAD

**Issue by bibinwils** [PyTorchLightning/pytorch-lightning#6426]
Not able to import PyTorch lightning to google colab
![image](https://user-images.githubusercontent.com/53151992/110414659-4aaa2580-80b6-11eb-9445-417417f111ea.png)

**Comment by higepon** [comment]
I'm also seeing this.
Did you find any workaround?

**Comment by Whisht** [comment]
The reason of this bug is because the new released torchtext 0.9 has moved `torchtext.data.Batch`  to `torchtext.legacy.data.Batch`. Just see https://github.com/pytorch/text/releases/tag/v0.9.0-rc5.

**Comment by higepon** [comment]
Thanks. Here is my short term solution for this issue.
`!sed -i -e 's/from torchtext.data/from torchtext.legacy.data/' /usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py`

**Comment by kaushikb11** [comment]
Hey guys, Similar Issue #6415.

The solution is either 

- You could install from master `pip install git+https://github.com/PyTorchLightning/pytorch-lightning`.
- Or, downgrade the `pytorch-lightning` version.

**Comment by tchaton** [comment]
Dear @higepon,

We just merged a fix for it. Should work fine in master and 1.2.3 coming out this week.

Closing this issue.

Best,
T.C
