### PR TITLE
Fix the case where logger=None is passed to Trainer

### PR DESCRIPTION
**Pull request by daniellepintz**
## What does this PR do?

Fixes a small bug introduced in https://github.com/PyTorchLightning/pytorch-lightning/pull/11920 for the case where logger=None is passed to the Trainer.

Before this PR, when logger=None is passed to the Trainer, we see this error:
```
    @property
    def log_dir(self) -> Optional[str]:
        if len(self.loggers) == 1:
            if isinstance(self.logger, TensorBoardLogger):
                dirpath = self.logger.log_dir
            else:
>               dirpath = self.logger.save_dir
E               AttributeError: 'NoneType' object has no attribute 'save_dir'
```

full output: https://gist.github.com/daniellepintz/f603473b82c1f21d8299eaae56b33001

This is because trainer.loggers is being set to `[None]` here: https://github.com/PyTorchLightning/pytorch-lightning/blob/5df519572f78ae5e23b0aab18fcbda06df7ff8dd/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py#L101
so in the `log_dir` property it thinks `len(self.loggers) == 1`.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

File: tests/loggers/test_all.py [hunk 1]
```diff
@@ -365,6 +365,16 @@ def _test_logger_created_on_rank_zero_only(tmpdir, logger_class):
...
 
 
+def test_none_logger(tmpdir):
+    """Tests the case where logger=None is passed to Trainer."""
+    model = BoringModel()
+    trainer = Trainer(
+        logger=None,
+        max_steps=1,
+    )
+    trainer.fit(model)
```
Comment (ananthsub) [inline tests/loggers/test_all.py:375]: You don't need to call trainer.fit 

Directly assert that trainer.logger, trainer.loggers, and trainer.log_dir return what's expected. This test case can cover logger=None, False, and []

File: tests/loggers/test_all.py [hunk 2]
```diff
@@ -365,6 +365,16 @@ def _test_logger_created_on_rank_zero_only(tmpdir, logger_class):
     assert trainer.state.finished, f"Training failed with {trainer.state}"
 
 
+def test_none_logger(tmpdir):
+    """Tests the case where logger=None is passed to Trainer."""
+    model = BoringModel()
+    trainer = Trainer(
+        logger=None,
```
Comment (ananthsub) [inline tests/loggers/test_all.py:372]: Technically this should be caught by a type checker since the trainer does explicitly allow for None to be passed in. Logger currently isn't an optional input

File: tests/loggers/test_all.py (hunk 1 above)
Comment (daniellepintz) [reply tests/loggers/test_all.py]: Updated!

File: tests/loggers/test_all.py (hunk 2 above)
Comment (akashkw) [reply tests/loggers/test_all.py:371]: Is it worth changing the type to `Optional` now? I think `logger=None` is something that people can mistakenly assume support exists for. The type checking warnings must not be obvious enough if this issue is coming up, so it could be simplest to just expand the types.

Comment (ananthsub) [reply tests/loggers/test_all.py:371]: Let's file an issue to discuss this. I think there's precedent for it given profiler accepts an optional input. But let's decouple that from this PR

File: tests/loggers/test_all.py [hunk 3]
```diff
@@ -365,6 +365,42 @@ def _test_logger_created_on_rank_zero_only(tmpdir, logger_class):
...
+def test_empty_list_logger(tmpdir):
+    """Tests the case where logger=[] is passed to Trainer."""
+    trainer = Trainer(
+        logger=[],
+        default_root_dir=tmpdir,
+        max_steps=1,
+    )
+    assert trainer.logger is None
+    assert trainer.loggers == []
+    assert trainer.log_dir == tmpdir
```
Comment (ananthsub) [inline tests/loggers/test_all.py:401]: you can merge these all into a single test case with pytest parametrize

**Review by krshrimali — APPROVED** [review]
LGTM, thanks for fixing this. ⚡ Before we forget about this, can you also creating an issue from [this](https://github.com/PyTorchLightning/pytorch-lightning/pull/12249#discussion_r820302681) comment?

**Review by ananthsub — APPROVED** [review]

**Review by rohitgr7 — APPROVED** [review]

File: tests/loggers/test_all.py (hunk 2 above)
Comment (daniellepintz) [reply tests/loggers/test_all.py]: https://github.com/PyTorchLightning/pytorch-lightning/issues/12259

File: tests/loggers/test_all.py [hunk 4]
```diff
@@ -365,6 +365,26 @@ def _test_logger_created_on_rank_zero_only(tmpdir, logger_class):
...
 
+@pytest.mark.parametrize(
+    "logger_value",
+    [
+        None,
+        False,
+        [],
+    ],
+)
+def test_no_logger(tmpdir, logger_value):
```
Comment (awaelchli) [inline tests/loggers/test_all.py:376]: this test would better fit into tests/trainer/flags. 
the tests here under test_all are meant to test the implementation of the logger api

**Review by awaelchli — APPROVED** [review]

File: tests/loggers/test_all.py (hunk 4 above)
Comment (daniellepintz) [reply tests/loggers/test_all.py]: good point. fixed!

File: tests/trainer/flags/test_logger.py [hunk 5]
```diff
@@ -0,0 +1,36 @@
+# Copyright The PyTorch Lightning team.
```
Comment (ananthsub) [inline tests/trainer/flags/test_logger.py:1]: what's the difference between this file and the one here? https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/trainer/properties/test_loggers.py

let's merge these together given they test the same things.

Comment (daniellepintz) [reply tests/trainer/flags/test_logger.py:1]: Technically one tests the Trainer properties and one tests the Trainer flags (constructor args). I can merge them if you want but they are technically different things.

Comment (ananthsub) [reply tests/trainer/flags/test_logger.py:1]: this is also asserting on the trainer properties to confirm the flags passed in work as expected. i think they're basically the same thing

Comment (daniellepintz) [reply tests/trainer/flags/test_logger.py]: you are totally right, sorry. updated.

**Review by Borda — APPROVED** [review]

**Review by Borda — COMMENTED** [review]
add chlog

**Comment by daniellepintz** [comment]
@carmocca @tchaton mind taking a look? Your review is needed to merge

File: CHANGELOG.md [hunk 6]
```diff
@@ -739,7 +739,10 @@ The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).
 - Fixed an issue that caused the Tuner to affect the random state ([#11870](https://github.com/PyTorchLightning/pytorch-lightning/pull/11870))
 
 
-- Fixed to avoid common hook warning if no hook is overridden ([#12131](https://github.com/PyTorchLightning/pytorch-lightning/pull/12131))
+- Fixed to avoid common hook warning if no hook is overridden ([#12131](https://github.com/PyTorchLightning/pytorch-lightning/pull/12131))]
```
Comment (carmocca) [inline CHANGELOG.md:742]:
```suggestion
- Fixed to avoid common hook warning if no hook is overridden ([#12131](https://github.com/PyTorchLightning/pytorch-lightning/pull/12131))
```

**Review by carmocca — APPROVED** [review]

**Comment by daniellepintz** [comment]
Ready to be merged!
