### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by dennisushi** [PyTorchLightning/pytorch-lightning#12324]
## 🐛 Bug

Can't import pytorch_lightning > 1.2

```    
from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/home/dennisushi/miniconda3/envs/calvin_venv/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/dennisushi/miniconda3/envs/calvin_venv/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```

Works OK with ==1.2.

### Expected behavior

No error

- PyTorch Lightning Version: 1.3.0-1.5.10
- PyTorch Version: 1.8-1.11
- Python version: 3.8
- OS (e.g., Linux):
- CUDA/cuDNN version: 
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): pip3
- Any other relevant information: in a Conda environment with these pip setup.py install requirements (not through conda)
```
cmake
wheel
numpy>1.2
hydra-core==1.1.1
hydra-colorlog
matplotlib
opencv-python
omegaconf
plotly
#pyhash
pytorch-lightning==1.4.9
torch==1.10.0
torchvision
#MulticoreTSNE
gitpython
scipy
sentence-transformers
setuptools==57.5.0
gym
moviepy
tqdm
termcolor
wandb
```

**Comment by akihironitta** [comment]
I think https://github.com/pytorch/pytorch/issues/69894 is the cause. I experienced the error before, and I remember using a different version of `setuptools` fixed the error. (I can't find the exact issue I saw before...)

**Comment by akihironitta** [comment]
@dennisushi Also, I remember the patch for this issue have been resolved in the PyTorch 1.11, so if you're okay with trying out the new version, I'd suggest doing so. Feel free to reopen this issue if the problem still persists.

**Comment by joaoplay** [comment]
> 

I was experiencing the same issue. Solved after upgrading to PyTorch 1.11.

**Comment by joaoplay** [comment]
> @dennisushi Also, I remember the patch for this issue have been resolved in the PyTorch 1.11, so if you're okay with trying out the new version, I'd suggest doing so. Feel free to reopen this issue if the problem still persists.

I was experiencing the same issue. Solved after upgrading to PyTorch 1.11. Thank you!
