### ISSUE TITLE
warm up LR causes crash

### ISSUE THREAD

**Issue by johngrabner** [PyTorchLightning/pytorch-lightning#2934]
My resnet encoder and transformer decoder are not training well.  So trying all kinds of stuff.
Latest attempt to improve is to use a warmup learning rate as described here: 
[https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/optimizers.rst](url)

My code is an exact copy:
```
    def optimizer_step(self, epoch_nb, batch_nb, optimizer, optimizer_i, opt_closure):
        if self.trainer.global_step < 500:
            lr_scale = min(1., float(self.trainer.global_step + 1) / 500.)
            for pg in optimizer.param_groups:
                pg['lr'] = lr_scale * self.hparams.learning_rate

                print(f"lr={pg['lr']}")
        optimizer.step()
        optimizer.zero_grad()
```

The crash is as follows:
```
Epoch 1:   0%|▍                                                                                                                     | 15/3544 [00:27<1:48:33,  1.85s/it, loss=nan, v_num=19]Traceback (most recent call last):
  File "kiss_transformer.py", line 539, in <module>
    trainer.fit(model, train_loader)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 34, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in fit
    self.accelerator_backend.train(model, nprocs=self.num_processes)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_spawn_backend.py", line 42, in train
    mp.spawn(self.ddp_train, nprocs=nprocs, args=(self.mp_queue, model,))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_spawn_backend.py", line 154, in ddp_train
    results = self.trainer.run_pretrain_routine(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1211, in run_pretrain_routine
    self.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 393, in train
    self.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 490, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 887, in run_training_batch
    grad_norm_dic = self.run_batch_backward_pass(split_batch, batch_idx, opt_idx, optimizer)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 948, in run_batch_backward_pass
    self.call_optimizer_step(optimizer, opt_idx, batch_idx, split_batch)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 986, in call_optimizer_step
    using_native_amp=native_amp)
TypeError: optimizer_step() got an unexpected keyword argument 'using_native_amp'

```

I have tried both these versions and same crash:
```
#RUN pip install pytorch-lightning==0.8.5
RUN pip install pytorch-lightning==0.9.0rc12
```

Not that I believe these things are related, but my code has the following:
```
        trainer = pl.Trainer(gpus=[0, 1],  accumulate_grad_batches=16, callbacks=[lr_logger]) #  
        trainer.fit(model, train_loader)
```

**Comment by johngrabner** [comment]
same crash even if gpu and accumulate gradient removed.
```
        trainer = pl.Trainer() #  gpus=[0, 1],  accumulate_grad_batches=16, callbacks=[lr_logger]
        trainer.fit(model, train_loader)
```

**Comment by johngrabner** [comment]
swapped optimizer, same crash
```
         optimizer = torch.optim.SGD(self.parameters(), lr=self.hparams.lr)
         #optimizer = torch.optim.Adam(self.parameters(), lr=self.hparams.lr)
```

**Comment by SkafteNicki** [comment]
This error (`TypeError: optimizer_step() got an unexpected keyword argument 'using_native_amp'`) states that you are missing arguments in when your are defining `optimizer_step`. From the docs, you can see that the call signature is this:

`optimizer_step(self, epoch, batch_idx, optimizer, optimizer_idx, second_order_closure=None, on_tpu=False, using_native_amp=False, using_lbfgs=False)`

https://pytorch-lightning.readthedocs.io/en/latest/lightning-module.html#optimizer-step

**Comment by johngrabner** [comment]
ok, 

First my version:
`print(f"pl__version__ {pl.__version__}")`
pl__version__ 0.9.0rc12

Copied example as the docs state.
```
    def optimizer_step(self, current_epoch, batch_idx, optimizer,
                    optimizer_idx, second_order_closure, on_tpu, using_native_amp, using_lbfgs):
        # warm up lr
        if self.trainer.global_step < 500:
            lr_scale = min(1., float(self.trainer.global_step + 1) / 500.)
            for pg in optimizer.param_groups:
                pg['lr'] = lr_scale * self.learning_rate

        # update params
        optimizer.step()
        optimizer.zero_grad()
```


```
Traceback (most recent call last):
  File "/home/john/Documents/GitHub/Offline_Handwriting_Recognition/Solutions/Aug2020_simple_transformer/src/kiss_transformer.py", line 249, in <module>
    trainer.fit(model, train_dataloader=train_loader, val_dataloaders=val_loader)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 34, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1017, in fit
    self.accelerator_backend.train(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 56, in train
    self.ddp_train(process_idx=self.task_idx, mp_queue=None, model=model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 219, in ddp_train
    results = self.trainer.run_pretrain_routine(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1211, in run_pretrain_routine
    self.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 393, in train
    self.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 490, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 887, in run_training_batch
    grad_norm_dic = self.run_batch_backward_pass(split_batch, batch_idx, opt_idx, optimizer)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 948, in run_batch_backward_pass
    self.call_optimizer_step(optimizer, opt_idx, batch_idx, split_batch)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 986, in call_optimizer_step
    using_native_amp=native_amp)
TypeError: optimizer_step() missing 2 required positional arguments: 'on_tpu' and 'using_lbfgs'
```

My trainer
```
trainer = pl.Trainer( gpus=[0, 1],  
                accumulate_grad_batches=16, 
                max_epochs=500, 
                check_val_every_n_epoch=1, 
                distributed_backend='ddp', 
                fast_dev_run=False)
```
Can I provide any more info?

**Comment by rohitgr7** [comment]
try:
```python
optimizer_step(self, current_epoch, batch_idx, optimizer, optimizer_idx, second_order_closure, using_native_amp):
```
or
```python
optimizer_step(self, current_epoch, batch_idx, optimizer, optimizer_idx, second_order_closure=None, on_tpu=False, using_native_amp=False, using_lbfgs=False)
## Add default values to these arguments in the definition as mentioned in docs to avoid this error.
```

**Comment by johngrabner** [comment]
Sorry, I do not follow.
I define a class that includes method def optimizer_step. 

  ```
 class JJG_Transformer(pl.LightningModule):

    def __init__(self, weights):
    def training_step(self, batch, batch_idx):
       ....
    def forward(self, batch_im, batch_letter_transformer_input): 
        .....
    def configure_optimizers(self):
        .....
     def optimizer_step(self, current_epoch, batch_idx, optimizer,
                   optimizer_idx, second_order_closure, on_tpu, using_native_amp, using_lbfgs):

```
 I assume pytorch_ligthning calls this method optimizer_step. Thank you for your help.

**Comment by williamFalcon** [comment]
```
class JJG_Transformer(pl.LightningModule):

  def __init__(self, weights):
  def training_step(self, batch, batch_idx):
     ....
  def forward(self, batch_im, batch_letter_transformer_input): 
      .....
  def configure_optimizers(self):
      .....
  def optimizer_step(self, current_epoch, batch_idx, optimizer, optimizer_idx, second_order_closure=None, on_tpu=False, using_native_amp=False, using_lbfgs=False)

```

**Comment by rohitgr7** [comment]
@jonashaag just add the defaults
`second_order_closure=None, on_tpu=False, using_native_amp=False, using_lbfgs=False`

**Comment by johngrabner** [comment]
Finally, I get it.

BTW, lightning is awesome.  Thank you for contributing this to society. Tried lighting for Multi GPU. Discovered I got tensorboard for free. Discovered I need batches larger than my GPU supported. No worry, just use accumulate_grad_batches in lightning.  Now I think I need warmup, and lightning is there too.  A side benefit, my code is more structured. Just awesome.

**Comment by murnanedaniel** [comment]
Since the update to v1.0.5, this technique ([and the instructions in the docs](https://pytorch-lightning.readthedocs.io/en/latest/optimizers.html?highlight=warm-up#step-optimizers-at-arbitrary-intervals)) breaks. Specifically, I get `TypeError: optimizer_step() got an unexpected keyword argument 'epoch'`, since the `optimizer_step()` call has changed to `self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)`. I can see how to re-organise `optimizer, opt_idx` and `batch_idx`, but what should one do with `train_step_and_backward_closure`? Default it to `None`?

**Comment by igorgad** [comment]
Also getting the same error `TypeError: optimizer_step() got an unexpected keyword argument 'epoch'`. Is the documentation not up to date yet?

**Comment by ytzhao** [comment]
Getting the same error TypeError: optimizer_step() got an unexpected keyword argument 'epoch' with pytorch lightning version 1.1.0. Is there any solutions?

**Comment by ytzhao** [comment]
> Also getting the same error `TypeError: optimizer_step() got an unexpected keyword argument 'epoch'`. Is the documentation not up to date yet?
> 
> BTW, Lightning has been great!

Hi @igorgad I got the same error `TypeError: optimizer_step() got an unexpected keyword argument 'epoch'` with pytorch lightning version 1.1.0. I fixed the problem by following steps:
1. override the `optimizer_step()` functions in this way: `def optimizer_step(self, epoch, batch_idx, optimizer, optimizer_idx, optimizer_closure, second_order_closure=None, on_tpu=False, using_native_amp=False, using_lbfgs=False):`
2. change `optimizer.step()` to `optimizer.step(closure=optimizer_closure)`

it works for me :)
