### ISSUE TITLE
Data is not moved to the correct device 

### ISSUE THREAD

**Issue by alealv** [PyTorchLightning/pytorch-lightning#13444]
## 🐛 Bug

Hi
I have a model which requires some _Data dependent Initialization_ (DDI). It only needs one example to configure correct starting weights for a certain layer. For that I have set the following hook in my LightningModule:

```python
    def on_fit_start(self) -> None:
        if self.ddi:
            for f in self.decoder.flows:
                if getattr(f, "set_ddi", False):
                    f.set_ddi(True)

            _LOGGER.info("Doing data-dependent model initialization")
            for batch in self.trainer.datamodule.train_dataloader():
                x, x_lengths, y, y_lengths, speaker_ids, _ = batch
                with torch.no_grad():
                    self.forward(x, x_lengths, y, y_lengths, g=speaker_ids)
                break
```

This was working fine in version 1.5 but it's now broken in version 1.6. I get:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
```

Debugging I found that data is on device `-1` which actually means all GPUs if I understand correctly. This is the case for both versions.

Also, although it works on version 1.5 `self.device` is invalid inside the forward method.
```
    x = self.emb(x) * torch.sqrt(torch.tensor([self.hidden_channels], device=self.device))  # [b, t, h]
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TextEncoder' object has no attribute 'device'
```

### To Reproduce
In whichever model just set the following hook:
```python
    def on_fit_start(self) -> None:
            for batch in self.trainer.datamodule.train_dataloader():
                with torch.no_grad():
                    self.forward(*batch)
                break
```

### Expected behavior

Data should be on the correct device

### Environment
```bash
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.23.0
        - pyTorch_debug:     False
        - pyTorch_version:   1.11.0+cu102
        - pytorch-lightning: 1.5.10  or 1.6.4
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
```

cc @justusschock @awaelchli @ninginthecloud @rohitgr7 @otaj

**Comment by awaelchli** [comment]
Since you are accessing the raw dataloader manually yourself, you need to move the data to the right device when you iterate over it. So here in your code example:

```py
def on_fit_start(self) -> None:
            for batch in self.trainer.datamodule.train_dataloader():
                with torch.no_grad():
                    # Add this (assuming batch is a tensor)
                    batch.to(self.device)
                    # self.forward(batch)  # dont do this
                    self(batch)  # do this
                break
```

> Also, although it works on version 1.5 self.device is invalid inside the forward method.

Yes, on a regular nn.Module this is not defined. You can only access it on a LightningModule.

**Comment by rohitgr7** [comment]
or rather just use
```py
batch = self.transfer_batch_to_device(batch, self.batch)
```
while will handle more types such as dict in case you have that.

**Comment by alealv** [comment]
Cool, thanks for all the answers! It seems that I got confused, the answer is very clear now.

I modified the code like this and its working

```diff
             for batch in self.trainer.datamodule.train_dataloader():
+                batch = self.transfer_batch_to_device(batch, self.device, 0)
                 x, x_lengths, y, y_lengths, speaker_ids, _ = batch
                 with torch.no_grad():
-                    self.forward(x, x_lengths, y, y_lengths, g=speaker_ids)
+                    self(x, x_lengths, y, y_lengths, g=speaker_ids)
                 break
```

Although, I have another doubt now about `dataloader_idx`. Are all dataloaders store in some iterable inside the DataModule, hence we need an index? What's the appropriate value? I don't find documentation very clear about it.

`dataloader_idx ([int](https://docs.python.org/3/library/functions.html#int)) – The index of the dataloader to which the batch belongs.`
