### ISSUE TITLE
fix DALI example

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#4918]
## 🐛 Bug

failing DALI example after upgrading to 0.28

```
self = <pl_examples.basic_examples.dali_image_classifier.DALIClassificationLoader object at 0x7f1180070b90> | 820s

| def __len__(self):
| batch_count = self._size // (self._num_gpus * self.batch_size)
| >       last_batch = 1 if self._fill_last_batch else 0
| E       AttributeError: 'DALIClassificationLoader' object has no attribute '_fill_last_batch'
| pl_examples/basic_examples/dali_image_classifier.py:104: AttributeError
```

### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/blob/94a9d3d2837eb962cb47ad2854569039a552f729/pl_examples/basic_examples/dali_image_classifier.py#L102-L105

### Additional context

it happened after v0.28 release
https://github.com/NVIDIA/DALI/releases/tag/v0.28.0

**Comment by gan3sh500** [comment]
@Borda I was able to fix the issue updating to new API. Some checks are failing. Is it due to your freezing DALI version?

**Comment by Borda** [comment]
> @Borda I was able to fix the issue updating to new API. Some checks are failing. Is it due to your freezing DALI version?

I guess not as we have some other problems with min libs config...

**Comment by gan3sh500** [comment]
I will check out the failing checks and try to fix it. If I'm stuck I will ask.
