### ISSUE TITLE
Test function

### ISSUE THREAD

**Issue by linhlevandlu** [PyTorchLightning/pytorch-lightning#2448]
Hello,
My model was worked well on version 0.7.3. Then, I have tried to update the version of pytorch-lightning to 0.8.3.
I have re-trained and tested my model. The training have passed well, but in method test(), I have meet an error:
```
Traceback (most recent call last):
  File "src/main_cv.py", line 283, in <module>
    main(hyperparams)
  File "src/main_cv.py", line 66, in main
    trainer.test()
  File "/home/vle/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in test
    model = self.get_model().load_from_checkpoint(ckpt_path)
  File "/home/vle/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 169, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, **kwargs)
  File "/home/vle/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model = cls(*cls_args, **cls_kwargs)
**TypeError: __init__() missing 3 required positional arguments: 'train_loader', 'valid_loader', and 'test_loader'**
```
Even I have defined test_dataloader function in my model. Could you check if it is a issue of trainer class?

This is my program:
```
train_loader, valid_loader, test_loader = create_dataloader(...) # I write this function to create the loaders
model = MyModel(hparams, train_loader, valid_loader, test_loader) # define the model and parse data
trainer = pl.Trainer(max_epochs =1 )
trainer.fit(model)
trainer.test()
```
Many thanks!

**Comment by olineumann** [comment]
From 0.7.3 to 0.8.3 the test method has changed. Now it has some more parameters. See
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1168-L1175
vs
https://github.com/PyTorchLightning/pytorch-lightning/blob/0.7.3/pytorch_lightning/trainer/trainer.py#L872

By the parameter `ckpt_path`, which could be a path to the checkpoint or 'best' or None, you can specify which model "verison" should be used. The default is 'best'! So it tries to load the best model from your training run. Because you pass more than only `hparams` to the `__init__` method it can't create the model. It's recommended to only use one single `hparams` dict as parameter for the models.

You can simply pass `ckpt_path=None` which should solve the issue because then the weights from the last run should be used instead of loading a checkpoint. I would recommend to put the creation of the data loaders in the `__init__` method of the model or (maybe in your case better) as a argument of the Trainer's `fit` and `test` method. See https://pytorch-lightning.readthedocs.io/en/latest/trainer.html

**Comment by Borda** [comment]
@linhlevandlu feel free to reopen if needed 🐰
