### PR TITLE
Support limit_mode_batches (int) for infinite dataloader

### LINKED ISSUE #2649: Integer limit_val_batches does not work with infinite DataLoader.
## 🐛 Bug

Documentation states that you can use limit_val_batches=100 (with integer value) to limit number of batches. However, when using IterableDataset I get the following error:
pytorch_lightning.utilities.exceptions.MisconfigurationException: When using an infinite DataLoader (e.g. with an IterableDataset or when DataLoader does not implement `__len__`) for `limit_val_batches`, `Trainer(limit_val_batches)` must be `0.0` or `1.0`.

### To Reproduce
Just use:
pl.Trainer(val_check_interval=10, limit_val_batches=100)

with infinite DataLoader.

### Expected behavior

Do only N (100 in this case) validation steps.

### Environment

* CUDA:
        - GPU:
                - GeForce GTX 1080 Ti
        - available:         True
        - version:           10.0.130
* Packages:
        - numpy:             1.17.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.3.1
        - pytorch-lightning: 0.8.5
        - tensorboard:       2.2.2
        - tqdm:              4.46.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.4
        - version:           #1 SMP Wed Mar 7 19:03:37 UTC 2018

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

Fixes #2649 

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

File: pytorch_lightning/trainer/data_loading.py [hunk 1]
```diff
@@ -306,20 +308,17 @@ def _reset_eval_dataloader(
...
-                elif limit_eval_batches not in (0.0, 1.0):
-                    raise MisconfigurationException(
-                        'When using an infinite DataLoader (e.g. with an IterableDataset'
-                        f' or when DataLoader does not implement `__len__`) for `limit_{mode}_batches`,'
-                        f' `Trainer(limit_{mode}_batches)` must be `0.0` or `1.0`.')
+                    elif limit_eval_batches not in (0.0, 1.0):
+                        raise MisconfigurationException(
+                            'When using an infinite DataLoader (e.g. with an IterableDataset'
+                            f' or when DataLoader does not implement `__len__`) for `limit_{mode}_batches`,'
+                            f' `Trainer(limit_{mode}_batches)` must be `0.0`, `1.0` or `int`')
```
Comment (rohitgr7) [inline pytorch_lightning/trainer/data_loading.py:321]: How can `limit_mode_batches = 0.0 or 1.0` for infinite dataloader?

Comment (ethanwharris) [reply pytorch_lightning/trainer/data_loading.py:321]: As far as I remember, a value of `0.0` should just run nothing and a value of `1.0` should run until the dataloader stops. If it is an actually infinite dataloader then it would just never end, so perhaps this should be written differently?

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:321]: yeah, as of now I just moved some if-else statements and with 0.0 it was neither working before nor it working now. I can change it as per requirement. But just like you said I agree it should work with both `0.0` and `int` and otherwise raise this exception with an updated statement here.

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:321]: and not just 1.0 but with every `0.0 < limit_mode_batches <= 1.0`

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:321]: @awaelchli what do you suggest here? I'll update and add tests accordingly.

Comment (ethanwharris) [reply pytorch_lightning/trainer/data_loading.py:321]: Hmm, we still need to support `limit_mode_batches = 1.0` for iterable datasets since you may want to just run until the iteration stops, without knowing the length of the dataloader ahead of time. I think the issue where this came up was #1252. I think this is what happens now as the enumerate call will just stop once the underlying iterator reaches a `StopIteration`.

Comment (ethanwharris) [reply pytorch_lightning/trainer/data_loading.py:321]: We could maybe have a warning when `limit_mode_batches = 1.0` to tell the user that this will go on until the iteration ends? (or just refer to them as something other than infinite dataloaders)

Comment (awaelchli) [reply pytorch_lightning/trainer/data_loading.py:321]: We have the same for val_check_interval=1.0, where we distinguish between 1.0 (float, 100% of epoch) and 1 (int, batch count). I think it is reasonable to differentiate using the type and the docs make it very clear with the examples. Regarding this exception message, I think it should be changed to "When using an IterableDataset (e.g. of infinite size ...". Or just not refer to inf dataset as Ethan suggested.

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:321]: and for non-iterable datasets should 0.0 be supported with inf dataloader?

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:321]: and separate exceptions for Iterable and inf dataset? For Iterable `1.0` is supported and for inf dataloader `0.0` and `int` is supported?

Comment (awaelchli) [reply pytorch_lightning/trainer/data_loading.py]: can you clarify. what would that look like? I don't know of any inf datasets that are not of type IterableDataset.

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py]: Neither do I, never seen one. To he honest, I didn't even know about `IterableDataset` before this point 😅. Well I guess, I'll revert recent commits and change the exception message as suggested by Ethan.

**Comment by rohitgr7** [comment]
Should I add supporting docs here? https://pytorch-lightning.readthedocs.io/en/stable/sequences.html?highlight=IterableDataset#iterable-datasets

**Comment by rohitgr7** [comment]
Shoud I add supporting docs here? https://pytorch-lightning.readthedocs.io/en/latest/sequences.html?highlight=IterableDataset#iterable-datasets

**Comment by rohitgr7** [comment]
Should I add supporting docs here? https://pytorch-lightning.readthedocs.io/en/latest/sequences.html?highlight=IterableDataset#iterable-datasets

File: CHANGELOG.md [hunk 2]
```diff
@@ -29,6 +29,8 @@ The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).
 
 - Added support for Mean in DDP Sync ([#2568](https://github.com/PyTorchLightning/pytorch-lightning/pull/2568))
 
+- Added support for `limit_{mode}_batches (int)` to work with infinite dataloader(IterableDataset) ([2787](https://github.com/PyTorchLightning/pytorch-lightning/pull/2787))
```
Comment (awaelchli) [inline CHANGELOG.md:32]:
```suggestion
- Added support for `limit_{mode}_batches (int)` to work with infinite dataloader (IterableDataset) ([2787](https://github.com/PyTorchLightning/pytorch-lightning/pull/2787))
```

Comment (rohitgr7) [reply CHANGELOG.md:32]: Will make these changes :)

Comment (Borda) [reply CHANGELOG.md]: you can just accept it here, so it may be easier them searching the lines in IDE, and also you can accept multiple suggestions as a single commit...

File: pytorch_lightning/trainer/data_loading.py [hunk 3]
```diff
@@ -212,18 +212,19 @@ def reset_train_dataloader(self, model: LightningModule) -> None:
...
-            if isinstance(self.limit_train_batches, float):
-                self.num_training_batches = len(self.train_dataloader)
-                self.num_training_batches = int(self.num_training_batches * self.limit_train_batches)
-            else:
-                self.num_training_batches = min(len(self.train_dataloader), self.limit_train_batches)
+        if isinstance(self.limit_train_batches, int) or self.limit_train_batches == 0.0:
+            self.num_training_batches = min(self.num_training_batches, int(self.limit_train_batches))
+        elif self.num_training_batches != float('inf'):
+            self.num_training_batches = int(self.num_training_batches * self.limit_train_batches)
+        elif self.limit_train_batches not in (0.0, 1.0):
```
Comment (ethanwharris) [inline pytorch_lightning/trainer/data_loading.py:223]:
```suggestion
        elif self.limit_train_batches != 1.0:
```

File: pytorch_lightning/trainer/data_loading.py [hunk 4]
```diff
@@ -308,20 +308,16 @@ def _reset_eval_dataloader(
...
-                        num_batches = int(num_batches * limit_eval_batches)
-                    else:
-                        num_batches = min(len(dataloader), limit_eval_batches)
-
+                # limit num batches either as a percent or num steps
+                if isinstance(limit_eval_batches, int) or limit_eval_batches == 0.0:
+                    num_batches = min(num_batches, int(limit_eval_batches))
+                elif num_batches != float('inf'):
+                    num_batches = int(num_batches * limit_eval_batches)
                 elif limit_eval_batches not in (0.0, 1.0):
```
Comment (ethanwharris) [inline pytorch_lightning/trainer/data_loading.py:316]:
```suggestion
                elif limit_eval_batches != 1.0:
```

File: docs/source/sequences.rst [hunk 5]
```diff
@@ -59,10 +59,13 @@ Iterable Datasets
...
-    (specifying the number of training batches to run before validation) when initializing the Trainer.
-    This is due to the fact that the IterableDataset does not have a __len__ and Lightning requires this to calculate
-    the validation interval when val_check_interval is less than one.
+.. note:: When using an IterableDataset you must set the val_check_interval to 1.0 (the default) or an int
+    (specifying the number of training batches to run before validation) when initializing the Trainer. This is
+    because the IterableDataset does not have a __len__ and Lightning requires this to calculate the validation
+    interval when val_check_interval is less than one. Similarly, you can set limit_{mode}_batches to a float or
+    an int. If it is set to 0.0 or 0 it will set num_{mode}_batches to 0, if it is an int it will set num_{mode}_batches
+    to limit_{mode}_batches, if it is set to 1.0 it will run for the whole dataset, otherwise it will throw an exception.
+    Here mode can be train/val/test.
```
Comment (Borda) [inline docs/source/sequences.rst:68]:
```suggestion
.. note:: When using an IterableDataset you must set the val_check_interval to 1.0 (the default) or an int
    (specifying the number of training batches to run before validation) when initializing the Trainer. This is
    because the IterableDataset does not have a ``__len__`` and Lightning requires this to calculate the validation
    interval when ``val_check_interval`` is less than one. Similarly, you can set limit_{mode}_batches to a float or
    an int. If it is set to 0.0 or 0 it will set ``num_{mode}_batches`` to 0, if it is an int it will set ``num_{mode}_batches``
    to ``limit_{mode}_batches``, if it is set to 1.0 it will run for the whole dataset, otherwise it will throw an exception.
    Here mode can be train/val/test.
```

File: pytorch_lightning/core/lightning.py [hunk 6]
```diff
@@ -1754,7 +1754,7 @@ def to_onnx(self, file_path: str, input_sample: Optional[Tensor] = None, **kwarg
         elif self.example_input_array is not None:
             input_data = self.example_input_array
         else:
-            raise ValueError(f'input_sample and example_input_array tensors are both missing.')
+            raise ValueError('input_sample and example_input_array tensors are both missing.')
```
Comment (Borda) [inline pytorch_lightning/core/lightning.py:1757]:
```suggestion
            raise ValueError('`input_sample` and `example_input_array` tensors are both missing.')
```

File: pytorch_lightning/trainer/data_loading.py [hunk 7]
```diff
@@ -308,20 +308,16 @@ def _reset_eval_dataloader(
...
+                elif num_batches != float('inf'):
+                    num_batches = int(num_batches * limit_eval_batches)
+                elif limit_eval_batches != 1.0:
                     raise MisconfigurationException(
-                        'When using an infinite DataLoader (e.g. with an IterableDataset'
-                        f' or when DataLoader does not implement `__len__`) for `limit_{mode}_batches`,'
-                        f' `Trainer(limit_{mode}_batches)` must be `0.0` or `1.0`.')
+                        'When using an IterableDataset for `limit_{mode}_batches`,'
+                        f' `Trainer(limit_{mode}_batches)` must be `0.0`, `1.0` or an int. An int k specifies'
+                        f' num_{mode}_batches to use.')
```
Comment (Borda) [inline pytorch_lightning/trainer/data_loading.py:320]:
```suggestion
                        f' `num_{mode}_batches` to use.')
```

File: pytorch_lightning/trainer/data_loading.py [hunk 8]
```diff
@@ -212,18 +212,19 @@ def reset_train_dataloader(self, model: LightningModule) -> None:
...
-            # try getting the length
-            if isinstance(self.limit_train_batches, float):
-                self.num_training_batches = len(self.train_dataloader)
-                self.num_training_batches = int(self.num_training_batches * self.limit_train_batches)
-            else:
-                self.num_training_batches = min(len(self.train_dataloader), self.limit_train_batches)
+        if isinstance(self.limit_train_batches, int) or self.limit_train_batches == 0.0:
+            self.num_training_batches = min(self.num_training_batches, int(self.limit_train_batches))
+        elif self.num_training_batches != float('inf'):
+            self.num_training_batches = int(self.num_training_batches * self.limit_train_batches)
```
Comment (Borda) [inline pytorch_lightning/trainer/data_loading.py:222]: can it be also `5.1` meaning 510% ?
cc: @PyTorchLightning/core-contributors

Comment (justusschock) [reply pytorch_lightning/trainer/data_loading.py:222]: @Borda I don't think so. We iterate like this:

```
# run epoch
        for batch_idx, (batch, is_last_batch) in self.profiler.profile_iterable(
                enumerate(_with_is_last(train_dataloader)), "get_train_batch"
        ):
            # stop epoch if we limited the number of training batches
            if batch_idx >= self.num_training_batches:
                break
```
so if the loader is exhausted before, this would trigger an stop iteration meaning that the condition will never be True.

Comment (Borda) [reply pytorch_lightning/trainer/data_loading.py:222]: still, it would be cleaner to have there `val = min(val, 1.0)`

Comment (rohitgr7) [reply pytorch_lightning/trainer/data_loading.py:223]: we can do _check_batch_limits there to avoid floating values > 1.0

**Comment by rohitgr7** [comment]
@Borda can we unmerge it there is some irrelevant code I just deleted locally and need to push it?

**Comment by Borda** [comment]
> @Borda can we unmerge it there is some irrelevant code I just deleted locally and need to push it? or should I create a new pr with updated changes?

yes, create a new PR and refer that it it fix to this one, lest get it done asap
